"""Pydantic schemas for proactive insights and notifications."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class InsightType(str, Enum):
    """Types of proactive insights."""
    HABIT_GAP = "habit_gap"           # Missing habit entries
    HABIT_STREAK = "habit_streak"      # Consecutive days achievement
    SLEEP_TREND = "sleep_trend"        # Sleep pattern analysis
    SLEEP_IRREGULAR = "sleep_irregular"  # Irregular sleep schedule
    CORRELATION = "correlation"        # Cross-data correlations
    EMAIL_IMPORTANT = "email_important"  # Important email detected
    DEADLINE_REMINDER = "deadline_reminder"  # Upcoming deadline
    PATTERN_DETECTED = "pattern_detected"  # Generic pattern


class InsightPriority(str, Enum):
    """Priority levels for insights."""
    LOW = "low"        # Nice to know, not urgent
    NORMAL = "normal"  # Should be aware
    HIGH = "high"      # Needs attention


class InsightAction(BaseModel):
    """Suggested action for an insight."""
    label: str = Field(..., description="Button label")
    intent: str = Field(..., description="Intent to execute")
    parameters: dict[str, Any] = Field(default_factory=dict)


class Insight(BaseModel):
    """A proactive insight generated by pattern analysis."""
    id: str = Field(..., description="Unique identifier (type_subject_date)")
    type: InsightType
    priority: InsightPriority = InsightPriority.NORMAL
    title: str = Field(..., max_length=50)
    message: str = Field(..., description="Sarcastic message from ATLAS")
    data: dict[str, Any] = Field(default_factory=dict, description="Raw data")
    created_at: datetime = Field(default_factory=datetime.now)
    dismissed: bool = False
    notified: bool = False
    actions: list[InsightAction] = Field(default_factory=list)

    class Config:
        use_enum_values = True


class InsightCreate(BaseModel):
    """Schema for creating a new insight."""
    type: InsightType
    priority: InsightPriority = InsightPriority.NORMAL
    title: str
    message: str
    data: dict[str, Any] = Field(default_factory=dict)
    actions: list[InsightAction] = Field(default_factory=list)


class NotificationType(str, Enum):
    """Types of push notifications."""
    BRIEFING = "briefing"
    INSIGHT = "insight"
    REMINDER = "reminder"
    ALERT = "alert"


class PushNotification(BaseModel):
    """Push notification to send to mobile."""
    type: NotificationType
    title: str
    body: str
    data: dict[str, Any] = Field(default_factory=dict)
    priority: str = "default"  # default | high


class AnalysisResult(BaseModel):
    """Result from an analyzer."""
    insights: list[Insight] = Field(default_factory=list)
    notifications: list[PushNotification] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
